### ISSUE TITLE
Add a link to GitHub repository

### ISSUE THREAD

**Issue by AlexWayfer** [Satont/gallery#4]
Hello.

I didn't find a link to this repository on the site. It'd be helpful.

**Comment by Satont** [comment]
Hi.

Where should i place that link? Do you think i need add new `about` page with description of application?

**Comment by AlexWayfer** [comment]
I think it'd look nice in the header, but as you wish. I mean… I can't imagine enough content for a separate `about` page.

**Comment by Satont** [comment]
This is good idea, i'll implement this in that way. 

Thank you.
